### PR TITLE
init source code

### LINKED ISSUE #3: Setup PWA
## Overview
As a developer, I should setup simple PWA that uses service worker. Use technologies defined in #1

### PR DESCRIPTION
**Pull request by linhnk-ips**
init source code.

### CODE REVIEW

**Comment by uveta** [comment]
Move all added files to **src/pwa** directory

**Review by SternUxi — CHANGES_REQUESTED** [review]
- Remove .env file from repository and add it to the .gitignore unless this is a method used by NextJS
- Use of Sass (node-sass) for styling so we can use variables and mixins
- Move font related imports inside App.js to eg. Styles/main.scss and import into app.js

**Comment by linhnk-ips** [comment]
> Move all added files to **src/pwa** directory

**Comment by linhnk-ips** [comment]
> Move all added files to **src/pwa** directory

I updated the structure to follow your idea. Please help me take a look again. Thanks

**Comment by linhnk-ips** [comment]
> * Remove .env file from repository and add it to the .gitignore unless this is a method used by NextJS
> * Use of Sass (node-sass) for styling so we can use variables and mixins
> * Move font related imports inside App.js to eg. Styles/main.scss and import into app.js

.env where we push app settings for each environment. ex: Dev, Pro ... So We still need it.

**Comment by thangbm** [comment]
> * Use of Sass (node-sass) for styling so we can use variables and mixins



Since we are using 'styled component' pattern on top of Emotion, I suggest to follow its principle/pattern until any issue being noticed or the needs to have SASS in place.

**Comment by uveta** [comment]
> > * Use of Sass (node-sass) for styling so we can use variables and mixins
> 
> Since we are using 'styled component' pattern on top of Emotion, I suggest to follow its principle/pattern until any issue being noticed or the needs to have SASS in place.

I agree, since we are using Emotion, no need to utilize SASS for now.

**Review by SternUxi — APPROVED** [review]

**Review by uveta — APPROVED** [review]

**Pull request merged**
